kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-app-memory
  namespace: hello-world
  labels:
    app: hello-app-memory
spec:  
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: hello-app-memory 
  template:
    metadata:
      labels:
        app: hello-app-memory
        tier: web
    spec:
      containers:
      - name: hello-app-memory
        image: fellipef/k8s-pipeline-2-memory:2.0.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 25Mi
          limits:
            memory: 100Mi