kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-app-cpu
  namespace: hello-world
  labels:
    app: hello-app-cpu
spec:  
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: hello-app-cpu 
  template:
    metadata:
      labels:
        app: hello-app-cpu
        tier: web
    spec:
      containers:
      - name: hello-app-cpu
        image: fellipef/k8s-pipeline-2-cpu:1.0.3
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 500m