kind: Service
apiVersion: v1
metadata:
  name: hello-app-cpu
  namespace: hello-world
  labels:
    app: hello-app-cpu
spec:
  selector:
    app: hello-app-cpu
    tier: web
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort